/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chandima.layered.view;

import chandima.layered.controller.FacilityController;
import chandima.layered.controller.RoomController;
import chandima.layered.dto.FacilityDto;
import chandima.layered.dto.RoomDto;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Student
 */
public class AdminView extends javax.swing.JFrame {

    FacilityController facilityController;
    RoomController roomController;
    /**
     * Creates new form AdminView
     */
    public AdminView() {
        facilityController=new FacilityController();
        roomController=new RoomController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jpnlCatrgories = new javax.swing.JPanel();
        jpnlPakeges = new javax.swing.JPanel();
        jpnlCustomer = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCusName = new javax.swing.JTextField();
        txtPassword2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCusAge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNIC1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcbCategory = new javax.swing.JComboBox<>();
        lblPasswordError = new javax.swing.JLabel();
        btnInsertUp = new javax.swing.JButton();
        btnUpdateCus = new javax.swing.JButton();
        btnDeleteCus = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        jpnlUsers = new javax.swing.JPanel();
        jpnlRoom = new javax.swing.JPanel();
        jpnlFacility = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbData = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlCatrgories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnlCatrgoriesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnlCatrgoriesLayout = new javax.swing.GroupLayout(jpnlCatrgories);
        jpnlCatrgories.setLayout(jpnlCatrgoriesLayout);
        jpnlCatrgoriesLayout.setHorizontalGroup(
            jpnlCatrgoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        jpnlCatrgoriesLayout.setVerticalGroup(
            jpnlCatrgoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Categories", jpnlCatrgories);

        jpnlPakeges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnlPakegesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnlPakegesLayout = new javax.swing.GroupLayout(jpnlPakeges);
        jpnlPakeges.setLayout(jpnlPakegesLayout);
        jpnlPakegesLayout.setHorizontalGroup(
            jpnlPakegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        jpnlPakegesLayout.setVerticalGroup(
            jpnlPakegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Packages", jpnlPakeges);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Customer Details");

        jLabel3.setText("Password");

        jLabel4.setText("Customer Name");

        txtCusName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCusNameFocusLost(evt);
            }
        });

        txtPassword2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassword2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassword2FocusLost(evt);
            }
        });
        txtPassword2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtPassword2InputMethodTextChanged(evt);
            }
        });

        jLabel5.setText("Re-enter Password");

        jLabel6.setText("Customer Age");

        jLabel7.setText("Customer NIC");

        jLabel8.setText("Category");

        jcbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Staff", "Admin", " ", " " }));

        lblPasswordError.setForeground(new java.awt.Color(102, 190, 87));
        lblPasswordError.setText("<html>\n\n</HTML>");
        lblPasswordError.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lblPasswordErrorFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(41, 41, 41)
                                    .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCusAge)
                                        .addComponent(jcbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(78, 78, 78)
                                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNIC1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblPasswordError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPasswordError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCusAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnInsertUp.setBackground(new java.awt.Color(51, 255, 255));
        btnInsertUp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInsertUp.setForeground(new java.awt.Color(0, 153, 153));
        btnInsertUp.setText("Insert");
        btnInsertUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertUpActionPerformed(evt);
            }
        });

        btnUpdateCus.setBackground(new java.awt.Color(51, 255, 255));
        btnUpdateCus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdateCus.setForeground(new java.awt.Color(0, 153, 153));
        btnUpdateCus.setText("Update");
        btnUpdateCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCusActionPerformed(evt);
            }
        });

        btnDeleteCus.setBackground(new java.awt.Color(51, 255, 255));
        btnDeleteCus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeleteCus.setForeground(new java.awt.Color(0, 153, 153));
        btnDeleteCus.setText("Delete");
        btnDeleteCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCusActionPerformed(evt);
            }
        });

        btnCancel1.setBackground(new java.awt.Color(51, 255, 255));
        btnCancel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancel1.setForeground(new java.awt.Color(0, 153, 153));
        btnCancel1.setText("Cancel");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlCustomerLayout = new javax.swing.GroupLayout(jpnlCustomer);
        jpnlCustomer.setLayout(jpnlCustomerLayout);
        jpnlCustomerLayout.setHorizontalGroup(
            jpnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsertUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateCus, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(btnDeleteCus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnlCustomerLayout.setVerticalGroup(
            jpnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCustomerLayout.createSequentialGroup()
                .addGroup(jpnlCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlCustomerLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnInsertUp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateCus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteCus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlCustomerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Customers", jpnlCustomer);

        javax.swing.GroupLayout jpnlUsersLayout = new javax.swing.GroupLayout(jpnlUsers);
        jpnlUsers.setLayout(jpnlUsersLayout);
        jpnlUsersLayout.setHorizontalGroup(
            jpnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        jpnlUsersLayout.setVerticalGroup(
            jpnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Users", jpnlUsers);

        javax.swing.GroupLayout jpnlRoomLayout = new javax.swing.GroupLayout(jpnlRoom);
        jpnlRoom.setLayout(jpnlRoomLayout);
        jpnlRoomLayout.setHorizontalGroup(
            jpnlRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        jpnlRoomLayout.setVerticalGroup(
            jpnlRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Room", jpnlRoom);

        jpnlFacility.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnlFacilityMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnlFacilityLayout = new javax.swing.GroupLayout(jpnlFacility);
        jpnlFacility.setLayout(jpnlFacilityLayout);
        jpnlFacilityLayout.setHorizontalGroup(
            jpnlFacilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        jpnlFacilityLayout.setVerticalGroup(
            jpnlFacilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Facility", jpnlFacility);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Admin Panel");

        jtbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtbData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        this.hide();
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void btnDeleteCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteCusActionPerformed

    private void btnUpdateCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateCusActionPerformed

    private void btnInsertUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertUpActionPerformed
        //signUp();
    }//GEN-LAST:event_btnInsertUpActionPerformed

    private void lblPasswordErrorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblPasswordErrorFocusGained

    }//GEN-LAST:event_lblPasswordErrorFocusGained

    private void txtPassword2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtPassword2InputMethodTextChanged

    }//GEN-LAST:event_txtPassword2InputMethodTextChanged

    private void txtPassword2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassword2FocusLost
        //validatePassword();
    }//GEN-LAST:event_txtPassword2FocusLost

    private void txtPassword2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassword2FocusGained

    }//GEN-LAST:event_txtPassword2FocusGained

    private void txtCusNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCusNameFocusLost

    }//GEN-LAST:event_txtCusNameFocusLost

    private void jpnlCatrgoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnlCatrgoriesMouseClicked
        loadTableCategories();
    }//GEN-LAST:event_jpnlCatrgoriesMouseClicked

    private void jpnlPakegesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnlPakegesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnlPakegesMouseClicked

    private void jpnlFacilityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnlFacilityMouseClicked
        loadTableFacilities();
    }//GEN-LAST:event_jpnlFacilityMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnDeleteCus;
    private javax.swing.JButton btnInsertUp;
    private javax.swing.JButton btnUpdateCus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbCategory;
    private javax.swing.JPanel jpnlCatrgories;
    private javax.swing.JPanel jpnlCustomer;
    private javax.swing.JPanel jpnlFacility;
    private javax.swing.JPanel jpnlPakeges;
    private javax.swing.JPanel jpnlRoom;
    private javax.swing.JPanel jpnlUsers;
    private javax.swing.JTable jtbData;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JTextField txtCusAge;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtNIC1;
    private javax.swing.JTextField txtPassword1;
    private javax.swing.JTextField txtPassword2;
    // End of variables declaration//GEN-END:variables

    private void loadTableCategories() {
        
    }
    
    private void loadTableFacilities() {
        try {
            //-------------Setting Table Coloums----------------------
            String[] col = {"Facility ID", "Facility Name", "Description"};
            DefaultTableModel dtm = new DefaultTableModel(col, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            jtbData.setModel(dtm);

            List<FacilityDto> facilityDtos = facilityController.getAllFacilities();
            System.out.println("Inserting data into rows in faciityView");
            for (FacilityDto facilityDto : facilityDtos) {
                System.out.println("for loop in roomView Data: " + facilityDto.getFacilityID());
                Object[] rowData = {
                    facilityDto.getFacilityID(),
                    facilityDto.getFacilityName(),
                    facilityDto.getDescription()
                };
                System.out.println("Adding Row data to JTB  in facilityView faclilityID:" + rowData.toString());
                dtm.addRow(rowData);
                System.out.println("---------------------------------------");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e);
        }
    }
    
    private void loadTableRoom() {
        try {
            String[] col = {"RoomID", "CategoryName", "NoOfPersons", "FloorNumber", "Price"};
            DefaultTableModel dtm = new DefaultTableModel(col, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            jtbData.setModel(dtm);

            List<RoomDto> roomDtos = roomController.getAllRooms();
            System.out.println("Inserting data into rows in roomView");
            for (RoomDto roomDto : roomDtos) {
                System.out.println("for loop in roomView Data: " + roomDto.getRoomID());
                Object[] rowData = {
                    roomDto.getRoomID(),
                    roomDto.getCategoryName(),
                    roomDto.getNoOfPersons(),
                    roomDto.getFloorNumber(),
                    roomDto.getPrice()
                };
                System.out.println("Adding Row data to JTB  in roomView RoomID:" + rowData.toString());
                dtm.addRow(rowData);
                System.out.println("---------------------------------------");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e);
        }

    }
}
