/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chandima.layered.view;

import chandima.layered.controller.CategoryController;
import chandima.layered.controller.FacilityController;
import chandima.layered.dto.CategoryDto;
import chandima.layered.dto.FacilityDto;
import chandima.layered.dto.RoomCategoryFacilitiesDto;
import chandima.layered.dto.UserDto;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Student
 */
public class ManageCategoriesView extends javax.swing.JFrame {

    private FacilityController facilityController;
    private CategoryController categoryController;

    private List<RoomCategoryFacilitiesDto> roomCategoryFacilitiesDtos = new ArrayList<>();

    /**
     * Creates new form ManageCategoriesView
     */
    public ManageCategoriesView() throws Exception {
        facilityController = new FacilityController();
        categoryController = new CategoryController();
        initComponents();
        loadTableFacilities();
        loadFacilities();
        loadComboBoxCategory() ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTbPFacility = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCatDescription = new javax.swing.JTextField();
        btnCatInsert = new javax.swing.JButton();
        btnCatCancel = new javax.swing.JButton();
        btnCatUpdate = new javax.swing.JButton();
        btnCatDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbFacilities = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtbFacilityCatogoty = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        cmbCatName = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtbFacility = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtFacilityID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFacilityName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtFacilityDescription = new javax.swing.JTextField();
        btnInsertFacility = new javax.swing.JButton();
        btnCancel4 = new javax.swing.JButton();
        btnUpdateFacility = new javax.swing.JButton();
        btnDeleteFacility = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("<html>Manage Category<br>&<br>Facilities</htm>");

        jTbPFacility.setBackground(new java.awt.Color(102, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Category"));

        jLabel5.setText("Category Name");

        jLabel3.setText("Description");

        btnCatInsert.setBackground(new java.awt.Color(51, 255, 255));
        btnCatInsert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCatInsert.setForeground(new java.awt.Color(0, 153, 153));
        btnCatInsert.setText("Insert Category");
        btnCatInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatInsertActionPerformed(evt);
            }
        });

        btnCatCancel.setBackground(new java.awt.Color(51, 255, 255));
        btnCatCancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCatCancel.setForeground(new java.awt.Color(0, 153, 153));
        btnCatCancel.setText("Cancel");
        btnCatCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatCancelActionPerformed(evt);
            }
        });

        btnCatUpdate.setBackground(new java.awt.Color(51, 255, 255));
        btnCatUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCatUpdate.setForeground(new java.awt.Color(0, 153, 153));
        btnCatUpdate.setText("Update Category");
        btnCatUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatUpdateActionPerformed(evt);
            }
        });

        btnCatDelete.setBackground(new java.awt.Color(51, 255, 255));
        btnCatDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCatDelete.setForeground(new java.awt.Color(0, 153, 153));
        btnCatDelete.setText("Delete Category");
        btnCatDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatDeleteActionPerformed(evt);
            }
        });

        jLabel6.setText("Select Facilities Included : ");

        cmbFacilities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtbFacilityCatogoty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jtbFacilityCatogoty);

        btnAdd.setBackground(new java.awt.Color(51, 255, 255));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 153, 153));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        cmbCatName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCatName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCatNameItemStateChanged(evt);
            }
        });
        cmbCatName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbCatNameFocusLost(evt);
            }
        });
        cmbCatName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cmbCatNameInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFacilities, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnCatDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCatCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCatDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                            .addComponent(cmbCatName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnCatInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnCatUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCatDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFacilities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCatUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCatCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTbPFacility.addTab("Category", jPanel2);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Facility"));

        jtbFacility.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbFacility.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbFacilityMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jtbFacility);

        jLabel16.setText("Facility ID");

        jLabel4.setText("Facility Name");

        jLabel17.setText("Description");

        btnInsertFacility.setBackground(new java.awt.Color(51, 255, 255));
        btnInsertFacility.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInsertFacility.setForeground(new java.awt.Color(0, 153, 153));
        btnInsertFacility.setText("Insert Facility");
        btnInsertFacility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertFacilityActionPerformed(evt);
            }
        });

        btnCancel4.setBackground(new java.awt.Color(51, 255, 255));
        btnCancel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancel4.setForeground(new java.awt.Color(0, 153, 153));
        btnCancel4.setText("Cancel");
        btnCancel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel4ActionPerformed(evt);
            }
        });

        btnUpdateFacility.setBackground(new java.awt.Color(51, 255, 255));
        btnUpdateFacility.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdateFacility.setForeground(new java.awt.Color(0, 153, 153));
        btnUpdateFacility.setText("Update Facility");
        btnUpdateFacility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFacilityActionPerformed(evt);
            }
        });

        btnDeleteFacility.setBackground(new java.awt.Color(51, 255, 255));
        btnDeleteFacility.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeleteFacility.setForeground(new java.awt.Color(0, 153, 153));
        btnDeleteFacility.setText("Delete Facility");
        btnDeleteFacility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFacilityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnDeleteFacility, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(btnInsertFacility, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnUpdateFacility, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel17))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFacilityDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtFacilityID, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFacilityName, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(16, 16, 16)))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtFacilityID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFacilityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFacilityDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertFacility, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateFacility, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteFacility, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTbPFacility.addTab("Facility", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTbPFacility, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTbPFacility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCatInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatInsertActionPerformed

    }//GEN-LAST:event_btnCatInsertActionPerformed

    private void btnCatCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatCancelActionPerformed
        this.hide();
    }//GEN-LAST:event_btnCatCancelActionPerformed

    private void btnCatUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatUpdateActionPerformed

    private void btnCatDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatDeleteActionPerformed

    private void btnInsertFacilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertFacilityActionPerformed
        insertFacility();
    }//GEN-LAST:event_btnInsertFacilityActionPerformed

    private void btnCancel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancel4ActionPerformed

    private void btnUpdateFacilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFacilityActionPerformed
        updateFacility();
    }//GEN-LAST:event_btnUpdateFacilityActionPerformed

    private void btnDeleteFacilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFacilityActionPerformed
        deleteFacility();
    }//GEN-LAST:event_btnDeleteFacilityActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addToTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbCatNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCatNameItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCatNameItemStateChanged

    private void cmbCatNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cmbCatNameInputMethodTextChanged
        //loadCategoryDes();
    }//GEN-LAST:event_cmbCatNameInputMethodTextChanged

    private void cmbCatNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbCatNameFocusLost
        loadCategoryDes();
    }//GEN-LAST:event_cmbCatNameFocusLost

    private void jtbFacilityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbFacilityMouseClicked
        selectFacility();
    }//GEN-LAST:event_jtbFacilityMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCategoriesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCategoriesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCategoriesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCategoriesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManageCategoriesView().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ManageCategoriesView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel4;
    private javax.swing.JButton btnCatCancel;
    private javax.swing.JButton btnCatDelete;
    private javax.swing.JButton btnCatInsert;
    private javax.swing.JButton btnCatUpdate;
    private javax.swing.JButton btnDeleteFacility;
    private javax.swing.JButton btnInsertFacility;
    private javax.swing.JButton btnUpdateFacility;
    private javax.swing.JComboBox<String> cmbCatName;
    private javax.swing.JComboBox<String> cmbFacilities;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTbPFacility;
    private javax.swing.JTable jtbFacility;
    private javax.swing.JTable jtbFacilityCatogoty;
    private javax.swing.JTextField txtCatDescription;
    private javax.swing.JTextField txtFacilityDescription;
    private javax.swing.JTextField txtFacilityID;
    private javax.swing.JTextField txtFacilityName;
    // End of variables declaration//GEN-END:variables

    private void loadFacilities() throws Exception {
        try {
            //-------------Setting Table Coloums----------------------
            String[] col = {"Facility ID", "Category Name"};
            DefaultTableModel dtm = new DefaultTableModel(col, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            jtbFacilityCatogoty.setModel(dtm);
            System.out.println("Set facility Table in facilityView");

            //----------------setting Data to Combo Box----------------
            List<FacilityDto> facilityDtos = facilityController.getAllFacilities();

            System.out.println("Data added to Dto in FacilityView");
            String facilityList[] = {"Select Item"};
            for (FacilityDto facilityDto : facilityDtos) {
                System.out.println("inside the for loop in FacilityView ID: " + facilityDto.getFacilityID());
                int x = 0;
                String temp[] = new String[facilityList.length + 1];
                for (; x < facilityList.length; x++) {
                    temp[x] = facilityList[x];
                }
                temp[x] = facilityDto.getFacilityName();
                facilityList = temp;
                System.out.println("In View : " + facilityDto.getFacilityName());
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(facilityList);
            cmbFacilities.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex);
        }
    }

    private void loadTableFacilities() {
        try {
            //-------------Setting Table Coloums----------------------
            String[] col = {"Facility ID", "Facility Name", "Description"};
            DefaultTableModel dtm = new DefaultTableModel(col, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            jtbFacility.setModel(dtm);

            List<FacilityDto> facilityDtos = facilityController.getAllFacilities();
            System.out.println("Inserting data into rows in faciityView");
            for (FacilityDto facilityDto : facilityDtos) {
                System.out.println("for loop in roomView Data: " + facilityDto.getFacilityID());
                Object[] rowData = {
                    facilityDto.getFacilityID(),
                    facilityDto.getFacilityName(),
                    facilityDto.getDescription()
                };
                System.out.println("Adding Row data to JTB  in facilityView faclilityID:" + rowData.toString());
                dtm.addRow(rowData);
                System.out.println("---------------------------------------");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e);
        }
    }

    private void loadComboBoxCategory() {
        try {
//        
            //----------------setting Data to Combo Box----------------
            System.out.println("Setting Data to combo box in CategoryView");
            List<CategoryDto> categoryDtos = categoryController.getAllCategories();

            System.out.println("Data added to Dto in CategoryView");
            String categoryList[] = {"Select Item"};
            for (CategoryDto categoryDto : categoryDtos) {
                System.out.println("inside the for loop in CategoryView ID: " + categoryDto.getCategoryName());
                int x = 0;
                String temp[] = new String[categoryList.length + 1];
                for (; x < categoryList.length; x++) {
                    temp[x] = categoryList[x];
                }
                temp[x] = categoryDto.getCategoryName();
                categoryList = temp;
                System.out.println("In View : " + categoryDto.getCategoryName());
            }

            DefaultComboBoxModel model = new DefaultComboBoxModel(categoryList);
            cmbCatName.setModel(model);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex);
        }
    }

    private void addToTable() {
        try {
            //-------------Adding Selected data to JTable----------------------
            RoomCategoryFacilitiesDto facilityCategoryDto = new RoomCategoryFacilitiesDto();
            FacilityDto tempDto = new FacilityDto();
            tempDto = facilityController.getFacility((String) cmbFacilities.getSelectedItem());
            facilityCategoryDto.setFacilityID(tempDto.getFacilityID());
            facilityCategoryDto.setCategoryName(cmbCatName.getSelectedItem().toString());

            //check duplicate value is in the table???????????????
            roomCategoryFacilitiesDtos.add(facilityCategoryDto);

            Object[] rowdata = {facilityCategoryDto.getFacilityID(), facilityCategoryDto.getCategoryName()};
            DefaultTableModel dtm = (DefaultTableModel) jtbFacilityCatogoty.getModel();
            dtm.addRow(rowdata);
            JOptionPane.showMessageDialog(this, "Success");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e);
        }
    }

    private void loadCategoryDes() {
        try {
            //----------------setting Data to textbox----------------
            if (cmbCatName.getSelectedItem().toString() != "Select Item") {
                CategoryDto categoryDto = categoryController.getCategory(cmbCatName.getSelectedItem().toString());

                txtCatDescription.setText(categoryDto.getDescription());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex);
        }
    }

    private void selectFacility() {
        try {
            //----------------selecting Jtable row to insert valuues to Form---------------
            String facilityID = jtbFacility.getValueAt(jtbFacility.getSelectedRow(), 1).toString();

            FacilityDto facilityDto = facilityController.getFacility(facilityID);

            txtFacilityID.setText(facilityDto.getFacilityID());
            txtFacilityName.setText(facilityDto.getFacilityName());
            txtFacilityDescription.setText(facilityDto.getDescription());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e);
        }
    }

    private void insertFacility() {
        try {
            //----------------Saving facility Data to database----------------
            FacilityDto facilityDto = new FacilityDto(
                    txtFacilityID.getText(),
                    txtFacilityName.getText(),
                    txtFacilityDescription.getText()
            );

            System.out.println(txtFacilityID.getText());
            System.out.println(txtFacilityName.getText());
            System.out.println(txtFacilityDescription.getText());

            String var = facilityController.saveFacility(facilityDto);
            JOptionPane.showMessageDialog(this, "Saving Facility :" + var);
            clearForm();
            loadTableFacilities();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e);
        }
    }

    private void clearForm() {
        //----------------clearing data of the form----------------
        txtFacilityID.setText("");
        txtFacilityName.setText("");
        txtFacilityDescription.setText("");
    }

    private void updateFacility() {
        //----------------updateing facility Data of the database----------------
        try {
            FacilityDto facilityDto = new FacilityDto(
                    txtFacilityID.getText(),
                    txtFacilityName.getText(),
                    txtFacilityDescription.getText()
            );

            String var = facilityController.updateFacility(facilityDto);
            JOptionPane.showMessageDialog(this, "Updating Facility :" + var);
            clearForm();
            loadTableFacilities();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e);
        }
    }

    private void deleteFacility() {
        try {
            String facilityID = txtFacilityID.getText();

            String var = facilityController.deleteFacility(facilityID);
            JOptionPane.showMessageDialog(this, "Deleting Facility :" + var);
            clearForm();
            loadTableFacilities();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e);
        }

    }

}
